//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doof.App.Resources.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Doof.App.Resources.Pages.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static string hero {
            get {
                return ResourceManager.GetString("hero", resourceCulture);
            }
        }
        
        internal static string hero_text {
            get {
                return ResourceManager.GetString("hero-text", resourceCulture);
            }
        }
        
        internal static string hero_button {
            get {
                return ResourceManager.GetString("hero-button", resourceCulture);
            }
        }
        
        internal static string why_1 {
            get {
                return ResourceManager.GetString("why-1", resourceCulture);
            }
        }
        
        internal static string why_2 {
            get {
                return ResourceManager.GetString("why-2", resourceCulture);
            }
        }
        
        internal static string why_3 {
            get {
                return ResourceManager.GetString("why-3", resourceCulture);
            }
        }
        
        internal static string why_title {
            get {
                return ResourceManager.GetString("why-title", resourceCulture);
            }
        }
        
        internal static string terry_title {
            get {
                return ResourceManager.GetString("terry-title", resourceCulture);
            }
        }
        
        internal static string terry_subtitle {
            get {
                return ResourceManager.GetString("terry-subtitle", resourceCulture);
            }
        }
        
        internal static string terry_1 {
            get {
                return ResourceManager.GetString("terry-1", resourceCulture);
            }
        }
        
        internal static string terry_2 {
            get {
                return ResourceManager.GetString("terry-2", resourceCulture);
            }
        }
        
        internal static string terry_3 {
            get {
                return ResourceManager.GetString("terry-3", resourceCulture);
            }
        }
    }
}
