// <auto-generated />
using System;
using Doof.App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Doof.App.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241029101029_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Doof.App.Features.Recipes.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        });
                });

            modelBuilder.Entity("Doof.App.Features.Recipes.IngredientTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.ToTable("IngredientTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IngredientId = 1,
                            IngredientName = "Bread",
                            Language = "en-US"
                        },
                        new
                        {
                            Id = 2,
                            IngredientId = 1,
                            IngredientName = "Bröd",
                            Language = "sv-SE"
                        },
                        new
                        {
                            Id = 3,
                            IngredientId = 1,
                            IngredientName = "パン",
                            Language = "ja-JP"
                        },
                        new
                        {
                            Id = 4,
                            IngredientId = 1,
                            IngredientName = "Pain",
                            Language = "fr-FR"
                        },
                        new
                        {
                            Id = 5,
                            IngredientId = 1,
                            IngredientName = "Pan",
                            Language = "es-ES"
                        },
                        new
                        {
                            Id = 6,
                            IngredientId = 2,
                            IngredientName = "Cheese",
                            Language = "en-US"
                        },
                        new
                        {
                            Id = 7,
                            IngredientId = 2,
                            IngredientName = "Ost",
                            Language = "sv-SE"
                        },
                        new
                        {
                            Id = 8,
                            IngredientId = 2,
                            IngredientName = "チーズ",
                            Language = "ja-JP"
                        },
                        new
                        {
                            Id = 9,
                            IngredientId = 2,
                            IngredientName = "Fromage",
                            Language = "fr-FR"
                        },
                        new
                        {
                            Id = 10,
                            IngredientId = 2,
                            IngredientName = "Queso",
                            Language = "es-ES"
                        });
                });

            modelBuilder.Entity("Doof.App.Features.Recipes.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = "3243c86d-7438-48cb-9a75-7d9bff08b725"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = "0462034d-8221-4cb2-8a68-db22c1028c5f"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = "647cb00f-ba4e-4c48-87a2-d91cf9936b29"
                        });
                });

            modelBuilder.Entity("Doof.App.Features.Recipes.RecipeImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RecipeId = 1,
                            Url = "https://doofstorage.blob.core.windows.net/recipes/1_1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            RecipeId = 1,
                            Url = "https://doofstorage.blob.core.windows.net/recipes/1_2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            RecipeId = 2,
                            Url = "https://doofstorage.blob.core.windows.net/recipes/2_1.jpg"
                        },
                        new
                        {
                            Id = 4,
                            RecipeId = 2,
                            Url = "https://doofstorage.blob.core.windows.net/recipes/2_2.jpg"
                        },
                        new
                        {
                            Id = 5,
                            RecipeId = 3,
                            Url = "https://doofstorage.blob.core.windows.net/recipes/3_1.jpg"
                        },
                        new
                        {
                            Id = 6,
                            RecipeId = 3,
                            Url = "https://doofstorage.blob.core.windows.net/recipes/3_2.jpg"
                        });
                });

            modelBuilder.Entity("Doof.App.Features.Recipes.RecipeStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeTranslationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StepNumber")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeTranslationId");

                    b.ToTable("RecipeSteps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Mix the flour, sugar, baking powder, and salt in a bowl.",
                            RecipeTranslationId = 1,
                            StepNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Add the milk, egg, and melted butter to the dry ingredients.",
                            RecipeTranslationId = 1,
                            StepNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Mix until smooth.",
                            RecipeTranslationId = 1,
                            StepNumber = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Heat a lightly oiled griddle or frying pan over medium-high heat.",
                            RecipeTranslationId = 1,
                            StepNumber = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "Pour or scoop the batter onto the griddle, using approximately 1/4 cup for each pancake.",
                            RecipeTranslationId = 1,
                            StepNumber = 5
                        },
                        new
                        {
                            Id = 6,
                            Description = "Brown on both sides and serve hot.",
                            RecipeTranslationId = 1,
                            StepNumber = 6
                        },
                        new
                        {
                            Id = 7,
                            Description = "Blanda mjöl, socker, bakpulver och salt i en skål.",
                            RecipeTranslationId = 2,
                            StepNumber = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "Tillsätt mjölk, ägg och smält smör till de torra ingredienserna.",
                            RecipeTranslationId = 2,
                            StepNumber = 2
                        },
                        new
                        {
                            Id = 9,
                            Description = "Blanda tills slät.",
                            RecipeTranslationId = 2,
                            StepNumber = 3
                        },
                        new
                        {
                            Id = 10,
                            Description = "Värm en lätt oljad stekpanna över medelhög värme.",
                            RecipeTranslationId = 2,
                            StepNumber = 4
                        },
                        new
                        {
                            Id = 11,
                            Description = "Häll eller skopa smeten på stekpannan, använd cirka 1/4 kopp för varje pannkaka.",
                            RecipeTranslationId = 2,
                            StepNumber = 5
                        },
                        new
                        {
                            Id = 12,
                            Description = "Bryn på båda sidor och servera varm.",
                            RecipeTranslationId = 2,
                            StepNumber = 6
                        },
                        new
                        {
                            Id = 13,
                            Description = "小麦粉、砂糖、ベーキングパウダー、塩をボウルに入れて混ぜます。",
                            RecipeTranslationId = 3,
                            StepNumber = 1
                        },
                        new
                        {
                            Id = 14,
                            Description = "牛乳、卵、溶かしバターを乾燥した材料に加えます。",
                            RecipeTranslationId = 3,
                            StepNumber = 2
                        },
                        new
                        {
                            Id = 15,
                            Description = "滑らかになるまで混ぜます。",
                            RecipeTranslationId = 3,
                            StepNumber = 3
                        },
                        new
                        {
                            Id = 16,
                            Description = "中火で軽くオイルを塗ったグリドルまたはフライパンを温めます。",
                            RecipeTranslationId = 3,
                            StepNumber = 4
                        },
                        new
                        {
                            Id = 17,
                            Description = "グリドルに生地を流し込み、各パンケーキに約1/4カップ使用します。",
                            RecipeTranslationId = 3,
                            StepNumber = 5
                        },
                        new
                        {
                            Id = 18,
                            Description = "両面を焼いて熱々で提供します。",
                            RecipeTranslationId = 3,
                            StepNumber = 6
                        },
                        new
                        {
                            Id = 19,
                            Description = "Mélanger la farine, le sucre, la levure chimique et le sel dans un bol.",
                            RecipeTranslationId = 4,
                            StepNumber = 1
                        },
                        new
                        {
                            Id = 20,
                            Description = "Ajouter le lait, l'œuf et le beurre fondu aux ingrédients secs.",
                            RecipeTranslationId = 4,
                            StepNumber = 2
                        },
                        new
                        {
                            Id = 21,
                            Description = "Mélanger jusqu'à obtenir une pâte lisse.",
                            RecipeTranslationId = 4,
                            StepNumber = 3
                        },
                        new
                        {
                            Id = 22,
                            Description = "Chauffer une poêle légèrement huilée à feu moyen-vif.",
                            RecipeTranslationId = 4,
                            StepNumber = 4
                        },
                        new
                        {
                            Id = 23,
                            Description = "Verser ou cuillère la pâte sur la poêle, en utilisant environ 1/4 de tasse pour chaque crêpe.",
                            RecipeTranslationId = 4,
                            StepNumber = 5
                        },
                        new
                        {
                            Id = 24,
                            Description = "Dorer des deux côtés et servir chaud.",
                            RecipeTranslationId = 4,
                            StepNumber = 6
                        },
                        new
                        {
                            Id = 25,
                            Description = "Mezclar la harina, el azúcar, el polvo de hornear y la sal en un tazón.",
                            RecipeTranslationId = 5,
                            StepNumber = 1
                        },
                        new
                        {
                            Id = 26,
                            Description = "Agregue la leche, el huevo y la mantequilla derretida a los ingredientes secos.",
                            RecipeTranslationId = 5,
                            StepNumber = 2
                        },
                        new
                        {
                            Id = 27,
                            Description = "Mezclar hasta que quede suave.",
                            RecipeTranslationId = 5,
                            StepNumber = 3
                        },
                        new
                        {
                            Id = 28,
                            Description = "Caliente una plancha ligeramente engrasada o una sartén a fuego medio-alto.",
                            RecipeTranslationId = 5,
                            StepNumber = 4
                        },
                        new
                        {
                            Id = 29,
                            Description = "Vierta o saque la masa en la plancha, usando aproximadamente 1/4 de taza para cada panqueque.",
                            RecipeTranslationId = 5,
                            StepNumber = 5
                        },
                        new
                        {
                            Id = 30,
                            Description = "Dore por ambos lados y sirva caliente.",
                            RecipeTranslationId = 5,
                            StepNumber = 6
                        });
                });

            modelBuilder.Entity("Doof.App.Features.Recipes.RecipeTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecipeSubTitle")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipeTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Language = "en-US",
                            RecipeId = 1,
                            RecipeSubTitle = "The best pancakes in the world",
                            RecipeTitle = "Pancakes"
                        },
                        new
                        {
                            Id = 2,
                            Language = "sv-SE",
                            RecipeId = 1,
                            RecipeSubTitle = "Världens bästa pannkakor",
                            RecipeTitle = "Pannkakor"
                        },
                        new
                        {
                            Id = 3,
                            Language = "ja-JP",
                            RecipeId = 1,
                            RecipeSubTitle = "世界で最高のパンケーキ",
                            RecipeTitle = "パンケーキ"
                        },
                        new
                        {
                            Id = 4,
                            Language = "fr-FR",
                            RecipeId = 1,
                            RecipeSubTitle = "Les meilleures crêpes du monde",
                            RecipeTitle = "Crêpes"
                        },
                        new
                        {
                            Id = 5,
                            Language = "es-ES",
                            RecipeId = 1,
                            RecipeSubTitle = "Los mejores panqueques del mundo",
                            RecipeTitle = "Panqueques"
                        },
                        new
                        {
                            Id = 6,
                            Language = "en-US",
                            RecipeId = 2,
                            RecipeSubTitle = "The best meatballs in the world",
                            RecipeTitle = "Meatballs"
                        },
                        new
                        {
                            Id = 7,
                            Language = "sv-SE",
                            RecipeId = 2,
                            RecipeSubTitle = "Världens bästa köttbullar",
                            RecipeTitle = "Köttbullar"
                        },
                        new
                        {
                            Id = 8,
                            Language = "ja-JP",
                            RecipeId = 2,
                            RecipeSubTitle = "世界で最高のミートボール",
                            RecipeTitle = "ミートボール"
                        },
                        new
                        {
                            Id = 9,
                            Language = "fr-FR",
                            RecipeId = 2,
                            RecipeSubTitle = "Les meilleures boulettes de viande du monde",
                            RecipeTitle = "Boulettes de viande"
                        },
                        new
                        {
                            Id = 10,
                            Language = "es-ES",
                            RecipeId = 2,
                            RecipeSubTitle = "Las mejores albóndigas del mundo",
                            RecipeTitle = "Albóndigas"
                        },
                        new
                        {
                            Id = 11,
                            Language = "en-US",
                            RecipeId = 3,
                            RecipeSubTitle = "The best tacos in the world",
                            RecipeTitle = "Tacos"
                        },
                        new
                        {
                            Id = 12,
                            Language = "sv-SE",
                            RecipeId = 3,
                            RecipeSubTitle = "Världens bästa tacos",
                            RecipeTitle = "Tacos"
                        },
                        new
                        {
                            Id = 13,
                            Language = "ja-JP",
                            RecipeId = 3,
                            RecipeSubTitle = "世界で最高のタコス",
                            RecipeTitle = "タコス"
                        },
                        new
                        {
                            Id = 14,
                            Language = "fr-FR",
                            RecipeId = 3,
                            RecipeSubTitle = "Les meilleurs tacos du monde",
                            RecipeTitle = "Tacos"
                        },
                        new
                        {
                            Id = 15,
                            Language = "es-ES",
                            RecipeId = 3,
                            RecipeSubTitle = "Los mejores tacos del mundo",
                            RecipeTitle = "Tacos"
                        });
                });

            modelBuilder.Entity("Doof.App.Features.Recipes.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnicodeEmoji")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UnicodeEmoji = "🍔"
                        });
                });

            modelBuilder.Entity("Doof.App.Features.Recipes.TagTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.ToTable("TagTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Language = "en-US",
                            TagId = 1,
                            TagName = "Burger"
                        },
                        new
                        {
                            Id = 2,
                            Language = "sv-SE",
                            TagId = 1,
                            TagName = "Hamburgare"
                        },
                        new
                        {
                            Id = 3,
                            Language = "ja-JP",
                            TagId = 1,
                            TagName = "バーガー"
                        },
                        new
                        {
                            Id = 4,
                            Language = "fr-FR",
                            TagId = 1,
                            TagName = "Hamburger"
                        },
                        new
                        {
                            Id = 5,
                            Language = "es-ES",
                            TagId = 1,
                            TagName = "Hamburguesa"
                        });
                });

            modelBuilder.Entity("IngredientRecipe", b =>
                {
                    b.Property<int>("IngredientsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IngredientsId", "RecipesId");

                    b.HasIndex("RecipesId");

                    b.ToTable("IngredientRecipe");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RecipeTag", b =>
                {
                    b.Property<int>("RecipesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecipesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("RecipeTag");
                });

            modelBuilder.Entity("Doof.App.Features.Users.CustomUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.HasDiscriminator().HasValue("CustomUser");

                    b.HasData(
                        new
                        {
                            Id = "3243c86d-7438-48cb-9a75-7d9bff08b725",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "52018cb5-8c28-4290-a9fb-aab4e69c2e2b",
                            Email = "adrian@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "ADRIAN@GMAIL.COM",
                            NormalizedUserName = "ADRIAN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDeBWVDhWEZXWDnzhKYn5nr09eNXGzFmo8+XmyRacTfq0+gWEKhg/VByhAYW01g+BA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "de7fee94-edc2-4cad-9dd3-5e60df8c8d27",
                            TwoFactorEnabled = false,
                            UserName = "adrian@gmail.com"
                        },
                        new
                        {
                            Id = "0462034d-8221-4cb2-8a68-db22c1028c5f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b4223ba4-460e-4bab-9a6c-c20e6ad32b40",
                            Email = "matilda@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "MATILDA@GMAIL.COM",
                            NormalizedUserName = "MATILDA@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPRN+2WhtFu8VJ/EXCje1RwKZdzys7S+HtnUhDcdwrzXP9H1m/5xnOo80aBTV543mQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "34301463-39b6-431f-be14-e85397baed88",
                            TwoFactorEnabled = false,
                            UserName = "matilda@gmail.com"
                        },
                        new
                        {
                            Id = "647cb00f-ba4e-4c48-87a2-d91cf9936b29",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c842f0e4-9398-41b2-ad03-6df8d1c632c0",
                            Email = "hans@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "HANS@GMAIL.COM",
                            NormalizedUserName = "HANS@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENaI82MmFB6+69cUmWKZgGqe2Y1dhT8078qidKLNhrk8lLWY3/FZJIJgsEFAKt82+A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a0992680-fe92-4439-8659-d5d729a21d4b",
                            TwoFactorEnabled = false,
                            UserName = "hans@gmail.com"
                        });
                });

            modelBuilder.Entity("Doof.App.Features.Recipes.IngredientTranslation", b =>
                {
                    b.HasOne("Doof.App.Features.Recipes.Ingredient", "Ingredient")
                        .WithMany("Translations")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("Doof.App.Features.Recipes.Recipe", b =>
                {
                    b.HasOne("Doof.App.Features.Users.CustomUser", "CustomUser")
                        .WithMany("Recipes")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomUser");
                });

            modelBuilder.Entity("Doof.App.Features.Recipes.RecipeImage", b =>
                {
                    b.HasOne("Doof.App.Features.Recipes.Recipe", "Recipe")
                        .WithMany("Images")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Doof.App.Features.Recipes.RecipeStep", b =>
                {
                    b.HasOne("Doof.App.Features.Recipes.RecipeTranslation", "RecipeTranslation")
                        .WithMany("Steps")
                        .HasForeignKey("RecipeTranslationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecipeTranslation");
                });

            modelBuilder.Entity("Doof.App.Features.Recipes.RecipeTranslation", b =>
                {
                    b.HasOne("Doof.App.Features.Recipes.Recipe", "Recipe")
                        .WithMany("Translations")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Doof.App.Features.Recipes.TagTranslation", b =>
                {
                    b.HasOne("Doof.App.Features.Recipes.Tag", "Tag")
                        .WithMany("Translations")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("IngredientRecipe", b =>
                {
                    b.HasOne("Doof.App.Features.Recipes.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Doof.App.Features.Recipes.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecipeTag", b =>
                {
                    b.HasOne("Doof.App.Features.Recipes.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Doof.App.Features.Recipes.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Doof.App.Features.Recipes.Ingredient", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Doof.App.Features.Recipes.Recipe", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Doof.App.Features.Recipes.RecipeTranslation", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Doof.App.Features.Recipes.Tag", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Doof.App.Features.Users.CustomUser", b =>
                {
                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
