//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doof.App.Resources.Pages.Account {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Login {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Login() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Doof.App.Resources.Pages.Account.Login", typeof(Login).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        internal static string meta_description {
            get {
                return ResourceManager.GetString("meta-description", resourceCulture);
            }
        }
        
        internal static string meta_keywords {
            get {
                return ResourceManager.GetString("meta-keywords", resourceCulture);
            }
        }
        
        internal static string email_placeholder {
            get {
                return ResourceManager.GetString("email-placeholder", resourceCulture);
            }
        }
        
        internal static string email_label {
            get {
                return ResourceManager.GetString("email-label", resourceCulture);
            }
        }
        
        internal static string password_placeholder {
            get {
                return ResourceManager.GetString("password-placeholder", resourceCulture);
            }
        }
        
        internal static string password_label {
            get {
                return ResourceManager.GetString("password-label", resourceCulture);
            }
        }
        
        internal static string remember_me {
            get {
                return ResourceManager.GetString("remember-me", resourceCulture);
            }
        }
        
        internal static string login_button {
            get {
                return ResourceManager.GetString("login-button", resourceCulture);
            }
        }
        
        internal static string forgot_password {
            get {
                return ResourceManager.GetString("forgot-password", resourceCulture);
            }
        }
        
        internal static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        internal static string resend_confirmation {
            get {
                return ResourceManager.GetString("resend-confirmation", resourceCulture);
            }
        }
        
        internal static string another_login {
            get {
                return ResourceManager.GetString("another-login", resourceCulture);
            }
        }
        
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        internal static string email_required {
            get {
                return ResourceManager.GetString("email-required", resourceCulture);
            }
        }
        
        internal static string email_valid {
            get {
                return ResourceManager.GetString("email-valid", resourceCulture);
            }
        }
        
        internal static string password_valid {
            get {
                return ResourceManager.GetString("password-valid", resourceCulture);
            }
        }
        
        internal static string password_required {
            get {
                return ResourceManager.GetString("password-required", resourceCulture);
            }
        }
    }
}
