name: Build and Deploy Application to VPS
on:
  push:
    branches:
      - main

jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Dotnet 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Display Dotnet Version
        run: dotnet --version

      - name: Restore Nuget Packages
        run: dotnet restore src

      - name: Build Application
        run: dotnet build src -c Release --no-restore

      - name: Publish Application
        run: dotnet publish src -c Release -o publish --no-restore

      # Upload the published files as an artifact for the deploy step
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: publish
          path: publish/

  # Deploy Job
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures this job runs after the build job completes
    steps:
      # Download the artifact generated by the build job
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: publish

      # Use SCP with rsync to copy files, excluding .env and database files
      - name: Copy files to VPS (Preserve .env and DB)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: ./publish/ # Directory containing the published files
          target: /home/adrian/doof/ # Target directory on the VPS
          rsync: true
          args: --exclude ".env" --exclude "*.db"  # Exclude .env and SQLite database files

      # SSH into the VPS and run deployment commands
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/adrian/doof
            sudo systemctl restart doof.service