name: Build and Deploy Application to VPS
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore Nuget Packages
        run: dotnet restore src

      - name: Build Application
        run: dotnet build src -c Release --no-restore

      - name: Publish Application
        run: dotnet publish src -c Release -o publish --no-restore

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: publish
          path: publish/

  # Deploy Job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: publish

      # Copy files to the server, excluding .env and DB
      - name: Copy files to VPS (Preserve .env and DB)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: "/home/runner/work/doof/doof/"
          target: "doof/code"
          rm: true

      # Restart the service
      - name: Restart doof Service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          # Might change
          script: echo "${{ secrets.PW }}" | sudo -S systemctl restart doof.service